create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk_100mhz]

set_property PACKAGE_PIN E3 [get_ports clk_100mhz]							
set_property IOSTANDARD LVCMOS33 [get_ports clk_100mhz]
 
 set_property PACKAGE_PIN A3 [get_ports {vgaRed[0]}]				
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[0]}]
    set_property PACKAGE_PIN B4 [get_ports {vgaRed[1]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[1]}]
    set_property PACKAGE_PIN C5 [get_ports {vgaRed[2]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[2]}]
    set_property PACKAGE_PIN A4 [get_ports {vgaRed[3]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[3]}]
    set_property PACKAGE_PIN B7 [get_ports {vgaBlue[0]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[0]}]
    set_property PACKAGE_PIN C7 [get_ports {vgaBlue[1]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[1]}]
    set_property PACKAGE_PIN D7 [get_ports {vgaBlue[2]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[2]}]
    set_property PACKAGE_PIN D8 [get_ports {vgaBlue[3]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[3]}]
    set_property PACKAGE_PIN C6 [get_ports {vgaGreen[0]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[0]}]
    set_property PACKAGE_PIN A5 [get_ports {vgaGreen[1]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[1]}]
    set_property PACKAGE_PIN B6 [get_ports {vgaGreen[2]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[2]}]
    set_property PACKAGE_PIN A6 [get_ports {vgaGreen[3]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[3]}]
    set_property PACKAGE_PIN B11 [get_ports Hsync]                        
        set_property IOSTANDARD LVCMOS33 [get_ports Hsync]
    set_property PACKAGE_PIN B12 [get_ports Vsync]                        
        set_property IOSTANDARD LVCMOS33 [get_ports Vsync]
        
set_property PACKAGE_PIN E16 [get_ports reset]							
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN V10 [get_ports serve]							
set_property IOSTANDARD LVCMOS33 [get_ports serve]

set_property PACKAGE_PIN P4 [get_ports up_sw1]							
set_property IOSTANDARD LVCMOS33 [get_ports up_sw1]
            
set_property PACKAGE_PIN P3 [get_ports down_sw1]							
set_property IOSTANDARD LVCMOS33 [get_ports down_sw1]
                        
set_property PACKAGE_PIN U8 [get_ports up_sw2]							
set_property IOSTANDARD LVCMOS33 [get_ports up_sw2]

set_property PACKAGE_PIN U9 [get_ports down_sw2]                            
set_property IOSTANDARD LVCMOS33 [get_ports down_sw2]

set_property PACKAGE_PIN L6 [get_ports {segments_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments_n[0]}]
set_property PACKAGE_PIN M2 [get_ports {segments_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments_n[1]}]
set_property PACKAGE_PIN K3 [get_ports {segments_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments_n[2]}]
set_property PACKAGE_PIN L4 [get_ports {segments_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments_n[3]}]
set_property PACKAGE_PIN L5 [get_ports {segments_n[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments_n[4]}]
set_property PACKAGE_PIN N1 [get_ports {segments_n[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments_n[5]}]
set_property PACKAGE_PIN L3 [get_ports {segments_n[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments_n[6]}]
set_property PACKAGE_PIN N6 [get_ports {an_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_n[0]}]
set_property PACKAGE_PIN M6 [get_ports {an_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_n[1]}]
set_property PACKAGE_PIN M3 [get_ports {an_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_n[2]}]
set_property PACKAGE_PIN N5 [get_ports {an_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_n[3]}]
set_property PACKAGE_PIN N2 [get_ports {an_n[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_n[4]}]
set_property PACKAGE_PIN N4 [get_ports {an_n[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_n[5]}]
set_property PACKAGE_PIN L1 [get_ports {an_n[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_n[6]}]
set_property PACKAGE_PIN M1 [get_ports {an_n[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_n[7]}]
